insert into disease_history.Patient (first_name,
                                     second_name,
                                     surname,
                                     birthday,
                                     address,
                                     passport,
                                     doctor,
                                     room)
values ('$first_name',
        '$second_name',
        '$surname',
        '$birthday',
        '$address',
        '$passport',
        '$doctor',
        '$room');